name: Docker Image CI

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
        DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
      run: |
        version="140.3"
        image_name="pschichtel/mindustry-server:v${version}"
        echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
        docker build . --file Dockerfile --build-arg=version="$version" --tag "$image_name"
        docker push "$image_name"

